export const USER_SET_ACTIVE_MODAL = 'USER_SET_ACTIVE_MODAL';
export const USER_SET_ACTIVE_TAB = 'USER_SET_ACTIVE_TAB';

export const USER_SET_ERROR = 'USER_SET_ERROR';
export const USER_SET_MESSAGE = 'USER_SET_MESSAGE';

export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAIL = 'USER_SIGN_UP_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_LOGIN_RECOVERY_REQUEST = 'USER_LOGIN_RECOVERY_REQUEST';
export const USER_LOGIN_RECOVERY_SUCCESS = 'USER_LOGIN_RECOVERY_SUCCESS';
export const USER_LOGIN_RECOVERY_FAIL = 'USER_LOGIN_RECOVERY_FAIL';

export const USER_CHANGE_PASS_REQUEST = 'USER_CHANGE_PASS_REQUEST';
export const USER_CHANGE_PASS_SUCCESS = 'USER_CHANGE_PASS_SUCCESS';
export const USER_CHANGE_PASS_FAIL = 'USER_CHANGE_PASS_FAIL';

export const USER_BALANCE_REQUEST = 'USER_BALANCE_REQUEST';
export const USER_BALANCE_SUCCESS = 'USER_BALANCE_SUCCESS';
export const USER_BALANCE_FAIL = 'USER_BALANCE_FAIL';

export const USER_WITHDRAW_REQUEST = 'USER_WITHDRAW_REQUEST';
export const USER_WITHDRAW_SUCCESS = 'USER_WITHDRAW_SUCCESS';
export const USER_WITHDRAW_FAIL = 'USER_WITHDRAW_FAIL';

//game
export const USER_SET_ACTIVE_FIELD = 'USER_SET_ACTIVE_FIELD';
export const USER_SET_ACTIVE_BET = 'USER_SET_ACTIVE_BET';
export const USER_SET_BETS = 'USER_SET_BETS';

export const USER_SUBMIT_BET = 'USER_SUBMIT_BET';
export const USER_SUBMIT_BET_NO_BALANCE = 'USER_SUBMIT_BET_NO_BALANCE';
export const USER_SUBMIT_BET_MAX_ECEEDED = 'USER_SUBMIT_BET_MAX_ECEEDED';

export const USER_SUBMIT_BET_SUCCESS = 'USER_SUBMIT_BET_SUCCESS';
export const USER_SUBMIT_BET_ERROR = 'USER_SUBMIT_BET_ERROR';